=== slowmountain/repovizz2doc/datatype_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "repovizz/datatype",
	"description": "JSON schema for repovizz datatype documents",
	"type": "object",
	"properties": {
		"datatypeID": {
			"description": "A UUID that gets automatically generated when the datatype document is uploaded",
			"$ref": "#/definitions/uuid"
		},
		"name": {
			"description": "The name of the datatype",
			"type": "string"
		},
		"parent": {
			"description": "The UUID of the datatype's parent, if applicable",
			"$ref": "#/definitions/uuid"
		},
		"owner": {
			"description": "Repovizz2 user that has authored the datatype document",
			"type": "string"
		},
		"description": {
			"description": "A textual description of the datatype",
			"type": "string"
		},
		"extra": {
			"type": "object"
		},
		"tags": {
			"description": "Tags to facilitate datatype search",
			"type": "array",
			"items": {"type": "string"},
			"uniqueItems": true
		},
		"datatype": {
			"description": "The datatype specification. One of [lattice, sparse, other]",
			"type": "object",
			"oneOf": [
				{
					"properties": {
						"lattice": {"$ref": "#/definitions/lattice"}
					},
					"required": ["lattice"],
					"additionalProperties": false
				},
				{
					"properties": {
						"sparse": {"$ref": "#/definitions/sparse"}
					},
					"required": ["sparse"],
					"additionalProperties": false
				}, 
				{
					"properties": {
						"other": {"$ref": "#/definitions/other"}
					},
					"required": ["other"],
					"additionalProperties": false
				}
			]
		}
	},
	"required": [
		"datatypeID",
		"name",
		"owner",
		"description",
		"tags",
		"datatype"
	],
	"additionalProperties": false,
	"definitions": {
		"uuid": {
			"description": "Universally unique identifier (UUID)",
			"type": "string",
			"pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
		},
		"lattice": {
			"description": "LATTICE datatypes describe continuous (fixed samplerate) data.",
			"type": "object",
			"properties": {
				"primary_dimensions": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"label": {
								"type": "string"
							},
							"units": {
								"type": "string"
							},
							"resolution": {
								"type": "number"
							},
							"description": {
								"type": "string"
							}
						},
						"required": [
							"label",
							"units",
							"resolution",
							"description"
						],
						"additionalProperties": false
					}
				},
				"secondary_dimensions": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"label": {
								"type": "string"
							},
							"units": {
								"type": "string"
							},
							"type": {
								"type": "string",
								"enum": [
									"boolean",
									"integer",
									"float"
								]
							},
							"description": {
								"type": "string"
							},
							"range": {
								"type": "object",
								"properties": {
									"min_val": {
										"type": "string"
									},
									"max_val": {
										"type": "string"
									}
								}
							}
						},
						"required": [
							"label",
							"units",
							"type",
							"description"
						],
						"additionalProperties": false
					}
				},
				"channels": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"description": {
								"type": "string"
							},
							"label": {
								"type": "string"
							}
						},
						"required": [
							"description",
							"label"
						],
						"additionalProperties": false
					}
				}
			},
			"required": [
				"primary_dimensions",
				"secondary_dimensions",
				"channels"
			],
			"additionalProperties": false
		},
		"sparse": {
			"description": "SPARSE datatypes describe sparsely/non-uniformly sampled data.",
			"type": "object",
			"properties": {
				"dimensions": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"label": {
								"type": "string"
							},
							"units": {
								"type": "string"
							},
							"description": {
								"type": "string"
							}
						},
						"required": [
							"label",
							"units",
							"description"
						],
						"additionalProperties": false
					}
				},
				"format": {
					"description": "TODO",
					"type": "object",
					"properties": {
						"primary_dimensions": {
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"label": {
										"type": "string"
									},
									"primaryDimension": {
										"type": "number"
									},
									"description": {
										"type": "string"
									}
								},
								"required": [
									"label",
									"primaryDimension",
									"description"
								],
								"additionalProperties": false
							}
						},
						"secondary_dimensions": {
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"label": {
										"type": "string"
									},
									"type": {
										"type": "string"
									},
									"description": {
										"type": "string"
									}
								},
								"required": [
									"label",
									"type",
									"description"
								],
								"additionalProperties": false
							}
						}
					},
					"required": [
						"primary_dimensions",
						"secondary_dimensions"
					],
					"additionalProperties": false
				}
			},
			"required": [
				"dimensions",
				"format"
			],
			"additionalProperties": false
		},
		"other": {
			"type": "object",
			"properties": {
				"MIME_type": {
					"type": "string"
				},
				"file_extension": {
					"type": "string"
				}
			},
			"required": [
				"MIME_type",
				"file_extension"
			],
			"additionalProperties": false
		}
	}
}

=== slowmountain/repovizz2doc/example_datatypes/monoaudio_datatype.json
{
    "datatypeID": "48e3b5d2-c34c-459c-9a2d-0756c20d80de",
    "name": "Mono 44100 audio",
    "owner": "ppapiotis",
    "description": "Mono audio recording at a sampling rate of 44100Hz.",
    "extra": {},
    "tags": ["audio", "mono"],
    "datatype": {
        "lattice": {
            "primary_dimensions": [{
                "label": "time",
                "units": "seconds",
                "resolution": 44100,
                "description": "time"
            }],
            "secondary_dimensions": [{
                "label": "Audio Intensity",
                "units": "a.u.",
                "type": "float",
                "description": "Audio intensity ranging from -1.0 to 1.0.",
                "range": {
                    "min_val": "-1.0",
                    "max_val": "1.0"
                }
            }],
            "channels": [{
                "description": "Mono",
                "label": "M"
            }]
        }
    }
}

=== slowmountain/repovizz2doc/example_datatypes/orientation_datatype.json
{
    "datatypeID": "35524338-dec5-40ca-a099-1fff42fb5460",
    "name": "Orientation (roll, pitch, yaw)",
    "owner": "ppapiotis",
    "description": "3-axis orientation derived from quaternion data",
    "extra": {},
    "tags": ["orientation"],
    "datatype": {
        "lattice": {
            "primary_dimensions": [{
                "label": "time",
                "units": "seconds",
                "resolution": 200,
                "description": "time"
            }],
            "secondary_dimensions": [{
                "label": "angle",
                "units": "radians",
                "type": "float",
                "description": "Angular value of the device's orientation."
            }],
            "channels": [{
                "description": "Roll (X) axis",
                "label": "Roll"
            }, {
                "description": "Pitch (Y) axis",
                "label": "Pitch"
            }, {
                "description": "Yaw (Z) axis",
                "label": "Yaw"
            }]
        }
    }
}

=== slowmountain/repovizz2doc/example_datatypes/gyroscope_datatype.json
{
    "datatypeID": "35524338-dec5-40ca-a099-1fff42fb5460",
    "name": "3-axis gyroscope",
    "owner": "ppapiotis",
    "description": "XYZ axis gyroscope data",
    "extra": {},
    "tags": ["gyroscope"],
    "datatype": {
        "lattice": {
            "primary_dimensions": [{
                "label": "time",
                "units": "seconds",
                "resolution": 200,
                "description": "time"
            }],
            "secondary_dimensions": [{
                "label": "angular velocity",
                "units": "radians/second",
                "type": "float",
                "description": "Angular velocity measured in radians per second."
            }],
            "channels": [{
                "description": "X axis",
                "label": "X"
            }, {
                "description": "Y axis",
                "label": "Y"
            }, {
                "description": "Z axis",
                "label": "Z"
            }]
        }
    }
}

=== slowmountain/repovizz2doc/example_datatypes/myo_emg_datatype.json
{
    "datatypeID": "0746bb48-9b92-4cd3-8d9e-3e1de13269eb",
    "name": "MYO 8-channel EMG",
    "owner": "ppapiotis",
    "description": "8-channel electromyography (EMG) data from Thalmic Labs' MYO sensor",
    "extra": {},
    "tags": ["EMG, MYO"],
    "datatype": {
        "lattice": {
            "primary_dimensions": [{
                "label": "time",
                "units": "seconds",
                "resolution": 200,
                "description": "time"
            }],
            "secondary_dimensions": [{
                "label": "Muscle activity",
                "units": "a.u.",
                "type": "integer",
                "description": "Arbitrary units of muscle activation ranging from -128 to 127.",
                "range": {
                    "min_val": "-128",
                    "max_val": "127"
                }
            }],
            "channels": [{
                "description": "Channel 1",
                "label": "1"
            }, {
                "description": "Channel 2",
                "label": "2"
            }, {
                "description": "Channel 3",
                "label": "3"
            }, {
                "description": "Channel 4",
                "label": "4"
            }, {
                "description": "Channel 5",
                "label": "5"
            }, {
                "description": "Channel 6",
                "label": "7"
            }, {
                "description": "Channel 7",
                "label": "7"
            }, {
                "description": "Channel 8",
                "label": "8"
            }]
        }
    }
}

=== slowmountain/repovizz2doc/example_datatypes/accelerometer_datatype.json
{
    "datatypeID": "ae13fb70-fa1e-47d8-9cd6-00cef4fe21cc",
    "name": "3-axis accelerometer",
    "owner": "ppapiotis",
    "description": "XYZ axis accelerometer data",
    "extra": {},
    "tags": ["accelerometer"],
    "datatype": {
        "lattice": {
            "primary_dimensions": [{
                "label": "time",
                "units": "seconds",
                "resolution": 200,
                "description": "time"
            }],
            "secondary_dimensions": [{
                "label": "acceleration",
                "units": "g",
                "type": "float",
                "description": "Acceleration measured in g (9.8 m/s^2)"
            }],
            "channels": [{
                "description": "X axis",
                "label": "X"
            }, {
                "description": "Y axis",
                "label": "Y"
            }, {
                "description": "Z axis",
                "label": "Z"
            }]
        }
    }
}
